language:
  python

notifications:
  email: false

python:
  - 3.6

install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install setuptools

script:
  - ./appserver.test.sh
  - python setup.py sdist

after_success:
  coveralls
