# Create container based on Python image
FROM python:2

# Install required dependencies
RUN pip install Flask

# Grab execution arguments
ARG ENV

# Define environment variables
ENV APPSERVER /appserver
ENV APPSERVER_CFG /appconfig

# Copy required files
COPY ./src/ ${APPSERVER}/
COPY ./runtime/config/${ENV}/ ${APPSERVER_CFG}/

# Open required ports
EXPOSE 8080

# Move into working dir for actual execution
WORKDIR ${APPSERVER}

# I guess this makes CMD commands run with python
ENTRYPOINT ["python"]

# Run application
CMD ["./container/app.py"]